spring:
  profiles:
    active: production
  thymeleaf:
    cache: false
hello: 1000
---
spring.profiles: production
server.port: 8080
spring:
  datasource:
    url: jdbc:mysql://xapple.csoxsytt9fev.ap-northeast-1.rds.amazonaws.com:3306/custom?useUnicode=true&characterEncoding=utf8
    username: root
    password: 10apple.com
    driverClassName: com.mysql.jdbc.Driver
    validation-query: SELECT 1
    test-while-idle: true
  jpa:
    hibernate:
      ddl-auto: update

---
spring.profiles: development
server.port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/custom?useUnicode=true&characterEncoding=utf8
    username: root
    password: admin
    driverClassName: com.mysql.jdbc.Driver
    validation-query: SELECT 1
    test-while-idle: true
  jpa:
    hibernate:
      ddl-auto: update

---